name: CI/CD Pipeline

on:
  push:
    branches:
      - develop # Update this with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Update this with your desired Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Build Docker image
        run: |
          docker build -t parkbrianjunsoo/maplanet_repository .
          docker tag parkbrianjunsoo/maplanet_repository:v1 parkbrianjunsoo/maplanet_repository:v1

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push parkbrianjunsoo/maplanet_repository:v1
