name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Update this with your desired Node.js version

      - name: Build Docker image
        run: |
          docker build -t parkbrianjunsoo/maplanet_repository:v1 .

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push parkbrianjunsoo/maplanet_repository:v1

      - name: Print Secrets
        run: echo $MY_ENV_VAR
        env:
          AWS_EC2_HOST: ${{ env.AWS_EC2_HOST }}
          AWS_EC2_USERNAME: ${{ env.AWS_EC2_USERNAME }}

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ env.AWS_EC2_HOST }}
            username: ${{ env.AWS_EC2_HOST }}
            key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
            script_stop: true
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/maplanet_repository:v1
              docker stop mapalnet-nest-app || true
              docker rm mapalnet-nest-app || true
              docker run -d --name my-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/maplanet_repository:v1
              EOF